version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: dep
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: dep
    schedule:
      interval: weekly
