version: 1
log_level: debug
dial_timeout: 10ms
tls:
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    ...
    -----END EC PRIVATE KEY-----
  client_cas: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  key_log_file: /tmp/keys
rules:
  - connect:
      address: localhost:8080
      network: tcp
    listen:
      address: localhost:4443
      network: tcp
