name: Validation

on:
  workflow_call:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ stable, oldstable ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test # runs all tests except those in the `integration` directory
        run: go list ./... | grep -v integration | xargs -d '\n' | go test -v
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ stable, oldstable ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v ./integration
  actions:
    name: Lint Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Set up linter
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Lint
        run: actionlint
  vet:
    name: Go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Vet
        run: go vet ./...
