name: Validation

on:
  workflow_call:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.X
      - name: Test # runs all tests except those in the `integration` directory
        run: go test -v $(go list ./... | grep -v integration)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.X
      - name: Test
        run: go test -v ./integration
